#!/bin/bash


src_dir=./src
include_dir=../include

cmd=$1
project_name=$2

if [ "$1" = "vim" ]
then 
	vim -On $src_dir/$project_name.cc $include_dir/$project_name.h
else
	./mk/build_scripts $project_name
fi


