#!/bin/bash

clear

src_name=$1

root=~/cpp/dev/
root=~/cpp/

bin=$root\bin/
inc=$root\include/
lib=$root\lib/
src=$root\net/src/
tes=$root\net/test/
mk=$root\net/mk/

tes_src=test_$src_name

test_file=$tes$tes_src.cc
src_file=$src$src_name.cc
exe_file=$bin$tes_src.o

lib_file=lib$src_name.so

rm $exe_file

#create lib.so
g++ $src_file					\
-g								\
-I $inc							\
-L $lib							\
-Wl,-rpath $lib					\
-fPIC -shared					\
-o $lib$lib_file

#create test.o
g++ $test_file					\
-g								\
-I $inc							\
-L $lib							\
-Wl,-rpath $lib					\
-l $src_name					\
-l Socket						\
-l pthread						\
-o $exe_file

chmod a+x $exe_file
$exe_file



